services:
  - type: web
    name: pet-adoption-backend
    env: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start  # Changed from "node dist/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true